---
- hosts: localhost
  gather_facts: False

  vars_files:
    - ./vars/aws_vault.yml
    - ./vars/aws_vars.yml

  environment:
    AWS_ACCESS_KEY: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    # or use aws_access_key/aws_secret_key parameters on ec2 module instead

  tasks:
    - name: example ec2 group
      amazon.aws.ec2_group:
        name: example_group
        description: an example EC2 group
        region: eu-central-1
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: security_group_results
    - name: Create an instance
      ec2:
        instance_type: t2.small
        image: ami-0502e817a62226e03
        wait: yes
        group_id: "{{ security_group_results.group_id }}"
        count: 1
        key_name: KnpU-Tutorial
        region: eu-central-1
        instance_tags:
          Name: MooTube instance
      # Could be useful further to get Public IP, DNS, etc.
      register: ec2

    # debug the output to see what AWS returns back
    - debug: var=ec2
