---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    instance_type: t2.small
    security_group: webservers_sg
    image: ami-0502e817a62226e03
    keypair: KnpU-Tutorial
    region: eu-central-1
    count: 1
  vars_files:
    - ./vars/aws_vault.yml
    - ./vars/aws_vars.yml

  tasks:
    - name: Create a security group
      amazon.aws.ec2_group:
        name: "{{ security_group }}"
        description: The webservers security group
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
    - name: Launch the new EC2 Instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        keypair: "{{ keypair }}"
#        count: "{{count}}"
        instance_tags:
          Type: webserver
        exact_count: 1
        count_tag: Type
      register: ec2
      tags:
        - ec2_instance
#    - name: Add tag to Instance(s)
#      ec2_tag:
#        aws_access_key: "{{ aws_access_key }}"
#        aws_secret_key: "{{ aws_secret_key }}"
#        resource: "{{ item.id }}"
#        region: "{{ region }}"
#        state: "present"
#      with_items: "{{ ec2.instances }}"
#      args:
#        tags:
#          Type: webserver
#      tags: ec2_instance_tag